import { CodePlayground, CodePlaygroundSnippets } from '.'
import { StoryObj, Meta } from '@storybook/react'

const meta: Meta<typeof CodePlayground> = {
  component: CodePlayground,
  tags: ['autodocs'],
  decorators: [
    (Story) => (
      <div className="m-auto w-full max-w-2xl">
        <Story />
      </div>
    ),
  ],
}

export default meta

type Story = StoryObj<typeof CodePlayground>

const snippets: CodePlaygroundSnippets = {
  typescript: {
    code: `const sdk = new SDK()
const users = await sdk.getUsers()
console.log(users)`,
  },
  python: {
    code: `import sdk
users = sdk.getUsers()
print(users)`,
  },
  go: {
    code: `package main
import "sdk"
users := sdk.getUsers()
fmt.Println(users)`,
  },
  ruby: {
    code: `require 'sdk'
users = sdk.getUsers()
puts users`,
  },
  postman: {
    code: `const sdk = new SDK()
const users = sdk.getUsers()
console.log(users)`,
  },
}

export const Default: Story = {
  args: {
    snippets,
    heading: (
      <div className="flex items-center gap-2.5 px-2 font-mono text-sm">
        <span className="text-blue-400">GET</span>{' '}
        <span className="text-muted">/users</span>
      </div>
    ),
    footer: (
      <div className="text-muted ml-auto text-sm">
        Code snippets generated by AI ✨
      </div>
    ),
  },
}

const kitchenSink = `function getFooBar(bar: FooType) : BarType {
  return bar
}

function getBarFoo(foo: BarType) : FooType {
  return foo
}

const fooBar = [
  { foo: 'foo', bar: 'bar' },
  { foo: 'foo', bar: 'bar' },
  { foo: 'foo', bar: 'bar' },
]

for (const foo of fooBar) {
  console.log(foo)
}
`

export const KitchenSink: Story = {
  args: {
    ...Default.args,
    snippets: { typescript: { code: kitchenSink } },
  },
}

export const NonCopyable: Story = {
  args: {
    ...Default.args,
    copyable: false,
  },
}

export const NoHeading: Story = {
  args: {
    ...Default.args,
    heading: null,
  },
}

export const NoFooter: Story = {
  args: {
    ...Default.args,
    footer: null,
  },
}

export const WithReallyLongCode: Story = {
  args: {
    ...Default.args,
    maxHeight: 400,
    snippets: {
      typescript: {
        code: `const foo = 'bar';
const bar = 'foo';
const baz = 'qux';
const qux = 'baz';
const quux = 'corge';
const grault = 'garply';
const waldo = 'fred';
const plugh = 'xyzzy';
const corge = 'thud';
const fooBar = [
  { foo: 'foo', bar: 'bar' },
  { foo: 'foo', bar: 'bar' },
  { foo: 'foo', bar: 'bar' },
]
for (const foo of fooBar) {
  console.log(foo)
}
const quux = 'corge';
const grault = 'garply';
const waldo = 'fred';
const plugh = 'xyzzy';
const corge = 'thud';
const fooBar = [
  { foo: 'foo', bar: 'bar' },
  { foo: 'foo', bar: 'bar' },
  { foo: 'foo', bar: 'bar' },
]
for (const foo of fooBar) {
  console.log(foo)
}`,
      },
    },
  },
}

export const WithSmallerContainer: Story = {
  args: {
    ...Default.args,
  },
  decorators: [
    (Story) => (
      <div className="w-full max-w-96">
        <Story />
      </div>
    ),
  ],
}

export const Loading: Story = {
  args: {
    ...Default.args,
    snippets: {
      typescript: {
        loading: true,
      },
    },
  },
}
