name: "Conventional Commits"

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  check:
    name: Check Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
