name: Ensure PR is up-to-date with main

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  check-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch main branch
        run: |
          git fetch origin main

      - name: Check if PR is up-to-date with main
        id: check_diff
        run: |
          if ! git diff --quiet HEAD origin/main; then
            echo "Pull request is not up-to-date with main."
            exit 1
          fi
          echo "Pull request is up-to-date with main."

      - name: Set Check Result
        if: failure()
        run: echo "The pull request must be up-to-date with main. Please rebase or merge main into this branch."
