name: Published Package Test

on:
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm pack

      - run: pnpm link ../ # This links the root package into the integration project
        working-directory: integration

      - run: pnpm install --no-frozen-lockfile
        working-directory: integration


      - run: pnpm test
        working-directory: integration
